Implement Kafka with mail client
ilisau/user-service pull request #11
Opened 2023-03-14 11:15 UTC by ilisau

In this PR I implemented Kafka to send messages to mail client and close #10

2023-03-14 13:07 UTC, h1alexbel requested changes

2023-03-14 13:07 UTC, h1alexbel commented on src/main/java/com/solvd/userservice/service/impl/UserServiceImpl.java
> +//                .flatMap(userRepository::save)
remove comments

2023-03-14 13:07 UTC, h1alexbel commented on src/main/java/com/solvd/userservice/web/kafka/KfProducerConfig.java
> +    public KafkaSender<String, Object> sender(SenderOptions<String, Object> senderOptions) {
why its object?

2023-03-14 13:07 UTC, h1alexbel commented on src/main/resources/kafka/producer.xml
> +    <bootstrapServers>localhost:9092</bootstrapServers>
host is hardcoded

2023-03-14 13:12 UTC, h1alexbel requested changes

2023-03-14 13:12 UTC, h1alexbel commented on src/main/java/com/solvd/userservice/web/kafka/MessageSenderImpl.java
> +                                "key",
why key is hardcoded?

2023-03-14 14:11 UTC, ilisau commented on src/main/java/com/solvd/userservice/web/kafka/KfProducerConfig.java
> +    public KafkaSender<String, Object> sender(SenderOptions<String, Object> senderOptions) {
because I can use sender for any type of objects, which would be serialized to json

2023-03-14 14:27 UTC, h1alexbel requested changes

2023-03-14 14:27 UTC, h1alexbel commented on src/main/java/com/solvd/userservice/web/kafka/MessageSenderImpl.java
> +    public Flux<SenderResult<Object>> sendMessage(String topic, int partition, String key, Object data) {
why type is ```Object```?

2023-03-15 05:30 UTC, h1alexbel requested changes

2023-03-15 05:30 UTC, h1alexbel commented on src/main/java/com/solvd/userservice/web/kafka/MessageSenderImpl.java
> +    public Flux<SenderResult<Object>> sendMessage(String topic, int partition, String key, MailDataDto data) {
why returned type is `Object`

2023-03-15 08:13 UTC, h1alexbel approved these changes
So far, so good

2023-03-15 08:13 UTC, merged